services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_Web
  #   ports:
  #     - "8080:5000"
  #   volumes:
  #     - shared-volume:/web
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # flower:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_Flower
  #   ports:
  #     - "5555:5555"
  #   links:
  #     - redis
  #   volumes:
  #     - .:/usr/src/app:ro
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=servision
      - POSTGRES_PASSWORD=servision
      - POSTGRES_DB=sv-jobs

volumes:
  shared-volume:
