services:
  web:
    build: .
    ports:
      - "8080:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  worker:
    build: .
    command: "celery -A main worker --loglevel=info"
    links:
      - redis
    volumes:
      - .:/usr/src/app:ro
  flower:
    build: .
    command: "celery -A main flower --loglevel=info"
    ports:
      - "5555:5555"
    links:
      - redis
    volumes:
      - .:/usr/src/app:ro
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=flask_celery
      - POSTGRES_USER=flask_celery
      - POSTGRES_PASSWORD=flask_celery
